name: CMake

on:
  # Trigger the workflow on push or pull request - but only for the main branch
  push:
    branches:
      - master
    tags-ignore:
      - 'v*'
  pull_request:
    branches:
      - master

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build-on-windows:
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    # windows-latest or windows-2022 fail!?
    runs-on: windows-2019

    steps:

    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 2
        submodules:  recursive

    - name: Configure Visual Studio and CMake
      working-directory: ${{runner.workspace}}
      run: |
          # setup the compiler
          cmd.exe /c "call `"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat`" && set > %temp%\vcvars.txt"
          Get-Content "$env:temp\vcvars.txt" | Foreach-Object { if ($_ -match "^(.*?)=(.*)$") { Set-Content "env:\$($matches[1])" $matches[2] } }
          # run cmake, looks v141_xp Toolset requires VS 2019
          cmake -G "Visual Studio 16 2019" -T v141_xp -A Win32 -S extio_rtl_tcp -B build

    - name: Build
      working-directory: ${{runner.workspace}}
      shell: bash
      run: cmake --build build --config $BUILD_TYPE

    #- name: Dir Listing
    #  working-directory: ${{runner.workspace}}
    #  shell: bash
    #  run: find . >src_listing.txt

    - name: Collect files to distribute
      working-directory: ${{runner.workspace}}
      shell: bash
      run: |
        cp "${{runner.workspace}}/extio_rtl_tcp/README.md" ./
        cp "${{runner.workspace}}/extio_rtl_tcp/README_RTL_TCP.txt" ./
        cp "${{runner.workspace}}/extio_rtl_tcp/LICENSE" ./
        cp "${{runner.workspace}}/build/Release/ExtIO_RTL_TCP.dll" ./

    - name: package and upload
      uses: actions/upload-artifact@v3
      with:
        name: extio_rtl_tcp
        path: |
            ${{runner.workspace}}/ExtIO_RTL_TCP.dll
            ${{runner.workspace}}/README.md
            ${{runner.workspace}}/README_RTL_TCP.txt
            ${{runner.workspace}}/LICENSE

