name: CMake

on:
  # Trigger the workflow on push or pull request - but only for the main branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build-on-windows:
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: windows-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Checkout submodules
      run: git submodule update --depth 1 --init --recursive

    - name: Configure CMake
      working-directory: ${{runner.workspace}}
      shell: bash
      # looks v141_xp Toolset requires VS 2019!
      run: cmake -G "Visual Studio 16 2019" -T v141_xp -A Win32 -S extio_rtl_tcp -B build

    - name: Build
      working-directory: ${{runner.workspace}}
      shell: bash
      run: cmake --build build --config $BUILD_TYPE

    #- name: Dir Listing
    #  working-directory: ${{runner.workspace}}
    #  shell: bash
    #  run: find . >src_listing.txt

    - name: Collect files to distribute
      working-directory: ${{runner.workspace}}
      shell: bash
      run: |
        cp "${{runner.workspace}}/extio_rtl_tcp/README.md" ./
        cp "${{runner.workspace}}/extio_rtl_tcp/LICENSE" ./
        cp "${{runner.workspace}}/build/Release/ExtIO_RTL_TCP.dll" ./

    - name: package and upload
      uses: actions/upload-artifact@v2
      with:
        name: extio_rtl_tcp
        path: |
            ${{runner.workspace}}/ExtIO_RTL_TCP.dll
            ${{runner.workspace}}/README.md
            ${{runner.workspace}}/LICENSE

